export const PROCESSING_STAGES = {
    DOWNLOADING: "DOWNLOADING",
    TRANSCODING: "TRANSCODING",
    TRANSCRIBING: "TRANSCRIBING",
    DIARIZING: "DIARIZING",
    SUMMARIZING: "SUMMARIZING",
    EMBEDDING: "EMBEDDING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
} as const;

export type ProcessingStage =
    (typeof PROCESSING_STAGES)[keyof typeof PROCESSING_STAGES];